apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: uit-cloud-exporter
  name: uit-cloud-exporter
  namespace: monitoring
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      port: uit-cloud-exporter
      relabelings:
        - action: replace
          separator: ;
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_endpoint_node_name
          targetLabel: node
        - action: replace
          separator: ;
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_host_ip
          targetLabel: host_ip

      scheme: http
      scrapeTimeout: 10s
  jobLabel: syst-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: uit-cloud-exporter

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: uit-cloud-exporter
  name: uit-cloud-exporter
  namespace: monitoring
spec:
  ports:
    - name: uit-cloud-exporter
      port: 9101
      protocol: TCP
      targetPort: 9101
  selector:
    app.kubernetes.io/name: uit-cloud-exporter
  sessionAffinity: None
  type: ClusterIP
