apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: uit-cloud-exporter
  name: uit-cloud-exporter
  namespace: monitoring
spec:
  ports:
  - name: uit-cloud-exporter
    port: 9101
    protocol: TCP
    targetPort: 9101
  selector:
    app.kubernetes.io/name: uit-cloud-exporter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}